CREATE TABLE `trip` (
	`tripId` BIGINT(15) NOT NULL AUTO_INCREMENT,
	`tripFileName` VARCHAR(100) NULL DEFAULT NULL,
	`tripPart` INT(2) NULL DEFAULT NULL,
	`tripStartDate` DATE NULL DEFAULT NULL,
	`tripStartTime` TIME NULL DEFAULT NULL,
	`tripEndDate` DATE NULL DEFAULT NULL,
	`tripEndTime` TIME NULL DEFAULT NULL,
	`tripPolygonStatus` INT(1) NULL DEFAULT NULL,
	`tripDistance` DECIMAL(10,3) NULL DEFAULT NULL,
	`tripDuration` INT(5) NULL DEFAULT NULL,
	`tripFirstLongitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripFirstLatitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripOriginLongitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripOriginLatitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripDestinationLongitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripDestinationLatitude` DECIMAL(20,10) NULL DEFAULT NULL,
	`tripOriginZone` VARCHAR(20) NULL DEFAULT NULL,
	`tripDestinationZone` VARCHAR(20) NULL DEFAULT NULL,
	`deviceId` VARCHAR(20) NULL DEFAULT NULL,
	`vehicleId` BIGINT(15) NULL DEFAULT NULL,
	`personId` BIGINT(15) NULL DEFAULT NULL,
	`tripDayWeek` INT(1) NULL DEFAULT NULL,
	`tripMaxSpeed` DECIMAL(5,0) NULL DEFAULT NULL,
	`tripFirst` INT(1) NULL DEFAULT NULL,
	`tripLast` INT(1) NULL DEFAULT NULL,
	`tripEngineStart` INT(1) NULL DEFAULT NULL,
	`tripMissing` INT(1) NULL DEFAULT NULL,
	`tripShowStatus` ENUM('0','1') NOT NULL DEFAULT '1',
	`tripDiaryStatus` ENUM('none','open','requested','provided') NULL DEFAULT 'none',
	`lastTripId` BIGINT(15) NULL DEFAULT NULL,
	`dataComplete` TINYINT(1) NULL DEFAULT '0',
	`tripHDOP` TINYINT(4) NULL DEFAULT NULL,
	`tripPDOP` TINYINT(4) NULL DEFAULT NULL,
	`tripSatNum` TINYINT(4) NULL DEFAULT NULL,
	`tripSpeedLimit` INT(3) NULL DEFAULT NULL,
	`tripCost` DECIMAL(9,2) NULL DEFAULT NULL,
	`tripEnergy` DECIMAL(9,2) NULL DEFAULT NULL,
	`tripType` ENUM('baseCase','15minBefore','30MinBefore','15MinAfter','30MinAfter','rail1','rail2','grta1','grta2','bike','walk','route1','route2','route3','transit1','transit2','trip','none') NULL DEFAULT 'trip',
	`jobId` BIGINT(11) NULL DEFAULT NULL,
	`lastModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`tripId`),
	INDEX `Index 2` (`tripFileName`)
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=247809
;